### PR TITLE
Added Chatbot

### PR DESCRIPTION
**Pull request by prajwal-144**
## Related Issue

- Chatbot 

## Proposed Changes 

- Chatbot using Deep Learning and Flask techniques. The chatbot is trained on a dataset containing categories (intents), pattern and responses. We use a special Artificial Neural Network (ANN) to classify which category the user’s message belongs to and then we give a random response from the list of responses.

## Additional Info

- Data preprocessing is by applying Lemmatization, Tokenization,etc. Loss at the end of training is near to 0.002.
- We can improve the model even further by adding more intents in the json file and also by applying other text preprocessing techniques like Named Entity Recognition, Vectorization, etc.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by cnu1812** [comment]
Hi @prajwal-144 awesome work. 👏👏. Just wanted to know do this allow live chat as well..?

**Comment by prajwal-144** [comment]
Hey, as of now it does not support live chat.
But surely can try in the future.

**Comment by prajwal-144** [comment]
Hey @cnu1812 is this okay or are some changes required?

**Comment by cnu1812** [comment]
> Hey @cnu1812 is this okay or are some changes required?

It's look okay for me, and I'm looping my team mate here @miguelbcodes for reviewing, once review is done will merge it. Thank you for your patience

**Review by miguelbcodes — APPROVED** [review]
It's awesome, great work @prajwal-144 !

**Pull request merged**
